languageCode = "en-us"
title = "Fisodd"
baseurl = "https://www.fisodd.com/"
theme = "hugo-b-side"

sectionPagesMenu = "main"
googleAnalytics = "UA-79887258-1"

[params]
  author = "Alexander Carlton"
  email = "mailto:AlexanderCarlton@fisodd.com"
  github = "https://www.github.com/fisodd"
  linkedin = "https://www.linkedin.com/in/AlexanderCarlton"
  license = "cc-by-sa-4.0"
