languageCode = "en-us"
title = "Fisodd"
baseurl = "http://www.fisodd.com/"
theme = "hugo-b-side"

sectionPagesMenu = "main"

[params]
  author = "Alexander Carlton"
  email = "mailto:AlexanderCarlton@fisodd.com"
  github = "https://www.github.com/fisodd"
  linkedin = "https://www.linkedin.com/in/AlexanderCarlton"

  license = "cc-by-sa-4.0"
